# Generated by Django 4.1.5 on 2023-01-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Category',
            new_name='category',
        ),
    ]
